version: '2'
services:

  app:
    build: ../
    volumes:
      - ../:/app
    depends_on:
      - redis

  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "43512:6379"

volumes:
  redis_data: